name: Create New Branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: create new branch
        run: |
          git checkout -b an-test
          git push --set-upstream origin an-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
