name: Create New Branch

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'The URL of the resume'
        required: false # or false, depending on your needs
        type: 'string' # if using a modern schema
      branch:
        description: 'The starting branch'
        required: true # or false, depending on your needs
        type: 'string'

jobs:
  createNewBranch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create new branch
        run: |
          echo ${{ inputs.branch }}
          git status
          # git checkout ${{ inputs.branch }}
          # git checkout -b ${{ inputs.branch }}-aqa
          # git push --set-upstream origin ${{ inputs.branch }}-aqa
          # Use curl to make the request (example uses a placeholder URL and GET method)
          curl -X POST \
             -H "Content-Type: application/json" \
             "$resumeUrl"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  call-n8n-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Send data back to n8n
        run: |
          originUrl="${{ inputs.resumeUrl }}"
          searchStr="http://localhost:5678/"
          replaceStr="https://test.omega.wizeline.io/"
          resumeUrl="${originUrl//$searchStr/$replaceStr}"
          echo $resumeUrl
          curl -X POST \
             -H "Content-Type: application/json" \
             "$resumeUrl"
